language: java
jdk: openjdk8
deploy:
  app: springboot-postgres-sudeep
  provider: heroku
  api_key:
    secure: NL18ha6uvdhVg2yabA5xWPeXWJQdQ0K8ZXURkT2OGA5PZCySo6Eoiar5ut6JaxxyELBRmzWcHRoyXYNdRk1gMdOU5ZnsGJ0OeZ4C6RUqeRmPeWd52nVlJawWcAomoQpxrLzVZxd7SebEAS8pHtR15prXBdBOOvOqmenJFCuBJ3H2MN4bZ8RUD5pO3a8/v6Ce1lCdQnF3HSPXJc19Bj7Ya11L3EYLW294LdresvuZFxkagS+kpM+yNHPGg9b++FvhNWqnPQRSvUZ0Sw9pOtB1V7SUa2Hv9SIG9+0ReuSqj1jtsd9DOUcX+A83n67nE6iDeU15XzkFVzx7KHGQggHB27O8Xk3kqP4ytzK5YByXOzZrZv4cZQVhvAMH65GASLUmPxqtJjoWxCDBVPVSi11FxIuAWx2PUEQdY6ISn9Gjp40DIwnGLn9YAdn2TIbmkEtQg/q4iCPBjnqh4xvJS+/qVMAUZR+CcD02PxrdqwUOesXG10O7jexzatJFeCvqOkk67vqwVKNUMhHAztSXiOiAIedTYdfUnKP67NCHbVT1+Xd29dq3gUdh/TCVvdlAIxaMrqm7mlCpxQuwEUCOz3L++X9og3FhIZ2gtt90Ff+gfW5Z4E4ZHlwEpW2mxh4cmzYb/XTAcaJcGXtyiuEv1h+CFgOYu+worWy49MmSknaGMYw=
